// Code generated by "stringer -type=Token"; DO NOT EDIT.

package nofox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenMoveRight-1]
	_ = x[TokenMoveLeft-2]
	_ = x[TokenIncrement-3]
	_ = x[TokenDecrement-4]
	_ = x[TokenPrint-5]
	_ = x[TokenRead-6]
	_ = x[TokenLoopStart-7]
	_ = x[TokenLoopEnd-8]
}

const _Token_name = "TokenEOFTokenMoveRightTokenMoveLeftTokenIncrementTokenDecrementTokenPrintTokenReadTokenLoopStartTokenLoopEnd"

var _Token_index = [...]uint8{0, 8, 22, 35, 49, 63, 73, 82, 96, 108}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
