// Code generated by "stringer -type=Type -output token_string.go -linecomment"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[MoveLeft-1]
	_ = x[MoveRight-2]
	_ = x[Decrement-3]
	_ = x[Increment-4]
	_ = x[Output-5]
	_ = x[Input-6]
	_ = x[JumpStart-7]
	_ = x[JumpBack-8]
	_ = x[Ignored-9]
}

const _Type_name = "eofmove_leftmove_rightdecrementincrementoutputinputjump_startjump_backignored"

var _Type_index = [...]uint8{0, 3, 12, 22, 31, 40, 46, 51, 61, 70, 77}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
